//
// Created by YE on 25. 10. 28..
//

#ifndef CLIONPROJECTSOOP2_TEAM8_ASSIGMENT_OPERATOR_H
#define CLIONPROJECTSOOP2_TEAM8_ASSIGMENT_OPERATOR_H


class operator {
};


#endif //CLIONPROJECTSOOP2_TEAM8_ASSIGMENT_OPERATOR_H